#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

node_modules/.bin/lint-staged && npm run test && npm run build
node_modules/.bin/lint-staged && npm run test && npm run build
node_modules/.bin/lint-staged && npm run test && npm run build
node_modules/.bin/lint-staged && npm run test && npm run build
node_modules/.bin/lint-staged && npm run test && npm run build
